version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: dotfiles
    main: ./cmd/dotfiles
    binary: dotfiles
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/enriikke/dotfiles/internal/cmd.Version={{.Version}}

archives:
  - id: dotfiles
    formats: ["tar.gz"]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: enriikke
    name: dotfiles
  draft: false
  prerelease: auto
