#!/bin/sh

sudo apt-get update
sudo apt-get install -y zsh npm
sudo chsh -s $(which zsh)

sudo apt-get install ripgrep
sudo apt-get install fzf

curl -sfL git.io/antibody | sh -s - -b /usr/local/bin

mkdir -p ~/.zsh
cp ./zsh/plugins ~/.zsh/plugins
cp ./.zshrc ~/.zshrc

source ~/.zshrc
