#!/bin/sh

sudo apt-get update
sudo apt-get install -y zsh npm
sudo chsh -s $(which zsh)

sudo apt-get install ripgrep
sudo apt-get install fzf

mkdir -p ~/.zsh
curl -L git.io/antigen > ~/.zsh/antigen.zsh
# git clone https://github.com/reobin/typewritten.git ~/.zsh/typewritten

cp ./.zshrc ~/.zshrc
cp ./.antigenrc ~/.zsh/.antigenrc

source ~/.zshrc
