#!/bin/sh

sudo apt-get update
sudo apt-get install -y zsh npm
sudo chsh -s $(which zsh)

sudo apt-get install ripgrep
sudo apt-get install fzf

curl -L git.io/antigen > ~/antigen.zsh
cp ./.zshrc ~/.zshrc
cp ./.antigenrc ~/.antigenrc
source ~/.zshrc
