#!/bin/bash

set -e

BLUE='\033[0;34m'
NC='\033[0m' # No Color

if ! command -v brew >/dev/null; then
  # installing homebrew
  echo -e "\n${BLUE}➡️ Installing Homebrew...\n${NC}"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  # make sure homebrew is in the path to continue
  export PATH="/usr/local/bin:$PATH"
else
  # updating homebrew
  echo -e "\n${BLUE}➡️ Updating Homebrew...\n${NC}"
  brew update
fi

# installing dependencies
echo -e "\n${BLUE}➡️ Installing Homebrew bundle...\n${NC}"
brew upgrade
brew bundle --file $(pwd -P)/dots/Brewfile
