#!/bin/sh

# updating apt-get
sudo apt-get update

# installing dependencies
sudo apt-get install -y ctags
sudo apt-get install -y fzf
sudo apt-get install -y gh
sudo apt-get install -y git
sudo apt-get install -y httpie
sudo apt-get install -y imagemagick
sudo apt-get install -y jq
sudo apt-get install -y neovim
sudo apt-get install -y ripgrep
sudo apt-get install -y tmux
sudo apt-get install -y tree
sudo apt-get install -y wget
sudo apt-get install -y zsh
