#!/bin/bash

set -x

# where am i?
WD=$(pwd -P)
if [ ! -f "$WD/script/setup" ]; then
  echo "whoa there! please run me from the root of the repo ☺️"
  exit 1
fi

# are we on a mac or GH codespace? bootstrap!
if [ $(uname -s) = "Darwin" ]; then
  $WD/script/bootstrap-mac
else
  apt-get update
  apt-get install -y ctags fzf gh git httpie imagemagick jq neovim ripgrep tmux tree wget zsh
fi

# copy dotfiles
mkdir -p ~/.config
ln -sfv $WD/dots/nvim ~/.config/nvim
ln -sfv $WD/dots/zsh ~/.config/zsh
ln -sfv $WD/dots/.gitconfig ~/.gitconfig
ln -sfv $WD/dots/.gitignore ~/.gitignore
ln -sfv $WD/dots/.tmux.conf ~/.tmux.conf
ln -sfv $WD/dots/.zshrc ~/.zshrc

# install antibody (zsh plugin manager)
# https://getantibody.github.io
curl -sfL git.io/antibody | sh -s - -b /usr/local/bin

# install vim-plug (vim plugin manager)
# https://github.com/junegunn/vim-plug
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
nvim +PlugInstall +qall

# change default shell to zsh
if [ "$SHELL" != $(which zsh) ]; then
  chsh -s $(which zsh)
fi

# load zsh and install plugins
source ~/.zshrc

# done
if [ -n $CODESPACES ]; then
  # git hooks magic
  [ -f /workspaces/github/script/git-hooks/pre-push ] && ln -s /workspaces/github/script/git-hooks/pre-push /workspaces/github/.git/hooks/pre-push

  # send notification that dotfiles setup has completed
  curl --silent \
    --form-string "token=$PUSHOVER_API_TOKEN" \
    --form-string "user=$PUSHOVER_USER_KEY" \
    --form-string "message=🎉 Codespace $CODESPACE_NAME is ready! ✨" \
    https://api.pushover.net/1/messages.json
fi
