#!/bin/sh

# ask for the administrator password upfront and keep `sudo` session alive
# sudo -s

# where am i?
if [ -L "$0" ]; then
  DIR=$(dirname $(readlink -f $0))
else
  DIR=$(dirname $0)
fi

WD=$(pwd)
cd $DIR/..
ROOT=$(pwd)
cd $WD

# are we on a mac or GH codespace? bootstrap!
if [ $(uname -s) = "Darwin" ]; then
  sh $ROOT/script/bootstrap-mac
else
  sh $ROOT/script/bootstrap-codespace
fi

# copy dotfiles
mkdir -p ~/.config
ln -sfv $ROOT/dots/nvim ~/.config/nvim
ln -sfv $ROOT/dots/zsh ~/.config/zsh
ln -sfv $ROOT/dots/.gitconfig ~/.gitconfig
ln -sfv $ROOT/dots/.gitignore ~/.gitignore
ln -sfv $ROOT/dots/.tmux.conf ~/.tmux.conf
ln -sfv $ROOT/dots/.zshrc ~/.zshrc

# install antibody (zsh plugin manager)
# https://getantibody.github.io
curl -sfL git.io/antibody | sudo sh -s - -b /usr/local/bin

# install vim-plug (vim plugin manager)
# https://github.com/junegunn/vim-plug
sudo sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

# change default shell to zsh
if [ "$SHELL" != $(which zsh) ]; then
  sudo chsh -s $(which zsh)
fi

# load zsh and install plugins
# source ~/.zshrc

# done
if [ -n $CODESPACES ]; then
  # git hooks magic
  [ -f $PWD/script/git-hooks/pre-push ] && ln -s $PWD/script/git-hooks/pre-push $PWD/.git/hooks/pre-push

  # send notification that dotfiles setup has completed
  curl --silent \
    --form-string "token=$PUSHOVER_API_TOKEN" \
    --form-string "user=$PUSHOVER_USER_KEY" \
    --form-string "message=🎉 Codespace $CODESPACE_NAME is ready! ✨" \
    https://api.pushover.net/1/messages.json
fi
